### ISSUE TITLE
Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1

### ISSUE THREAD

**Issue by mukulsoftwap** [bengfarrell/installing-node-opencv#1]
I am using windows 10 64 bit

opencv : 2.4.13
node : 6.9.1
npm : 3.10.8

Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mukulsoftwap\Desktop\opencv\node_modules\opencv
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN facetry@0.0.1 No repository field.
npm WARN facetry@0.0.1 No license field.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "opencv" "--save-dev" "--msvs_version=2013"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! opencv@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@1.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mukulsoftwap\Desktop\opencv\npm-debug.log

**Comment by bengfarrell** [comment]
Not sure. Haven't tried in ages, not since Node v0.8. That said, it doesn't look like it has anything to do with node-opencv specifically since there are no C++ compile errors. Mostly looks like you're having basic issues with node-gyp. Try npm installing a more popular package that needs to be built via node-gyp like websocket (https://www.npmjs.com/package/websocket). There should be more support/issues/etc that you can pull from to insure that node-gyp is working. I think the real issue is around Win10 and Visual Studio tooling being a moving target as time passes and making sure you have the right components installed
